// Re-export from new location for backward compatibility
export {
  hasKeychainSupport,
  getKeychainCredentials,
  saveToKeychain,
  clearKeychain,
  loadConfig,
  saveConfig,
  clearConfigFile,
  clearConfig,
  getCredentialsFromEnv,
  getCredentialsFromFile,
  getCredentials,
  hasCredentialsSync,
  hasCredentials,
  promptLogin,
  requireCredentials,
  type CredentialSource,
  type Config,
} from './shared/config.js';
